"""fixed schema

Revision ID: 4076152400da
Revises: cf5a82d2eda4
Create Date: 2021-05-23 18:06:11.232327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4076152400da'
down_revision = 'cf5a82d2eda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('description', sa.String(length=255), nullable=False))
    op.drop_index('date_added', table_name='location')
    op.create_unique_constraint(None, 'location', ['description'])
    op.drop_column('location', 'office_contact')
    op.drop_column('location', 'dept')
    op.drop_column('location', 'personal_contact')
    op.drop_column('location', 'personal_contact_secondary')
    op.drop_column('location', 'office_contact_secondary')
    op.drop_column('location', 'date_added')
    op.drop_column('location', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('location', sa.Column('date_added', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('location', sa.Column('office_contact_secondary', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('location', sa.Column('personal_contact_secondary', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('location', sa.Column('personal_contact', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('location', sa.Column('dept', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('location', sa.Column('office_contact', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'location', type_='unique')
    op.create_index('date_added', 'location', ['date_added'], unique=False)
    op.drop_column('location', 'description')
    # ### end Alembic commands ###
